dist: xenial
language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3

before_install:
  - travis_retry composer self-update

install: travis_retry travis_retry composer update --no-interaction --prefer-dist

script: vendor/bin/phpunit
